{
 "title": "FastAPI Monitoring Dashboard",
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(http_requests_total)" }
   ]
  },
  {
   "title": "Requests Over Time",
   "type": "graph",
   "gridPos": { "x": 6, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Avg Prediction Latency (s)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{path=\"/predict\"}[1m]) / rate(http_request_duration_seconds_count{path=\"/predict\"}[1m])"
    }
   ]
  },
  {
   "title": "Latency Over Time",
   "type": "graph",
   "gridPos": { "x": 6, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}