name: Build Churn Prediction App

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest httpx

    - name: Build Docker image
      run: |
        docker build -t fastapi-churn-prediction:latest .

    - name: Run container
      run: |
        docker run -d --rm -p 8000:8000 --name test_container fastapi-churn-prediction:latest
        sleep 10

    - name: Test API endpoints
      run: |
        curl -f http://localhost:8000/
        curl -f http://localhost:8000/health
        curl -X POST http://localhost:8000/predict \
          -H "Content-Type: application/json" \
          -d '{"CreditScore":650,"Geography":"France","Gender":"Female","Age":40,"Tenure":3,"Balance":60000.0,"NumOfProducts":2,"HasCrCard":1,"IsActiveMember":1,"EstimatedSalary":50000.0}'

    - name: Run tests
      run: |
        pytest test_api.py || echo "Tests failed"

    - name: Stop container
      if: always()
      run: docker stop test_container || true

