name: CI/CD Pipeline Deploy to AWS ECR and EC2

on:
  push:
    branches:
      - cicd_actions

env:
  ECR_REPO: churn-prediction
  IMAGE_TAG: suhaila245

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run Unit Tests
      run: pytest test.py

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: |
        IMAGE_URI="${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}"
        echo "Building Docker image $IMAGE_URI"
        docker build -t $IMAGE_URI .

    - name: Push Docker Image to ECR
      run: |
        IMAGE_URI="${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}"
        docker push $IMAGE_URI

    - name: Output image URI
      run: echo "Docker image pushed: $IMAGE_URI"
