name: Build and Test FastAPI Docker

on:
  push:
    branches:
      - cicd_actions
  pull_request:
    branches:
      - cicd_actions

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python (for test dependencies)
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest httpx

    - name: Build Docker image
      run: |
        docker build -t fastapi-churn-prediction:latest .

    # Optional: Log in and push to Docker Hub
    - name: Log in to Docker Hub
      if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
      run: |
        docker tag fastapi-churn-prediction:latest ${{ secrets.DOCKER_USERNAME }}/fastapi-churn-prediction:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-churn-prediction:latest

    - name: Run container in background
      run: |
        docker run -d --rm -p 8000:8000 --name test_container fastapi-churn-prediction:latest
        sleep 10  # wait for server to start

    - name: Test API endpoint
      run: |
        curl -f http://localhost:8000/health

    - name: Run pytest tests (if any)
      run: |
        pytest test_api.py || echo "Tests failed"

    - name: Stop container
      if: always()
      run: docker stop test_container
